shared:
  image: node:18
  steps:
    - echo: echo "test"

parameters:
  success: [' ', 'true', 'false']

jobs:
  downstream-hub:
    requires: [ ~sd@22684:hub ]
    annotations:
      screwdriver.cd/virtualJob: true
  downstream-success1:
    requires: [ ~downstream-hub ]
    annotations:
      screwdriver.cd/virtualJob: true
  downstream-success2:
    requires: [ ~downstream-hub ]
    annotations:
      screwdriver.cd/virtualJob: true
  downstream-failure1:
    requires: [ ~downstream-hub ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success.value)" != 'true' ]; then
            exit 1
          fi
  downstream-failure2:
    requires: [ ~downstream-hub ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success.value)" != 'true' ]; then
            exit 1
          fi
