shared:
  image: node:18
  steps:
    - echo: echo "test"
  annotations:
    screwdriver.cd/virtualJob: true

jobs:
  hub:
    requires: [ ~commit ]
  target-ss:
    requires: [ sd@22683:downstream-success1, sd@22683:downstream-success2 ]
  target-ff:
    requires: [ sd@22683:downstream-failure1, sd@22683:downstream-failure2 ]
