shared:
  image: node:18
  steps:
    - echo: echo "test"
  annotations:
    screwdriver.cd/virtualJob: true

jobs:
  downstream-hub:
    requires: [ ~sd@22673:hub ]
  downstream-a:
    requires: [ ~downstream-hub ]
  downstream-b:
    requires: [ ~downstream-hub ]
